config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  devise_for :admins
  get 'master/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products' => 'products#index'
  root 'products#index'

  get 'admins/top'
  get 'admins/products' => 'admins#productindex'
  delete 'admins/products/:id' => 'admins#productdestroy', as: 'admins_destroy'


  get 'admins' => 'admins#index'
  get 'admins/:id' => 'admins#usershow', as: 'admins_usershow'
  patch 'admins/:id' => 'admins#userupdate', as: 'admins_userupdate'
  get 'admins/:id/edit' => 'admins#useredit', as: 'admins_useredit'
  delete 'admins/:id/destroy' => 'admins#userdestroy', as: 'admins_userdestroy'

  post 'artists' => 'artists#create'
  get 'artist' => 'master#new'

  post 'genres' => 'genres#create'
  get 'genre' => 'master#new'

  post 'labels' => 'labels#create'
  get 'label' => 'master#new'

  post 'scenes' => 'scenes#create'
  get 'scene' => 'master#new'

  get 'contact' => 'products#contact'
  
  get 'products/new' => 'products#new'
  post 'products' => 'products#create'

  get 'products/:id/edit' => 'products#edit', as: 'product'
  # post 'products' => 'products#update'
  patch '/products/:id' => 'products#update', as: 'update_product'
  get 'products/:id' => 'products#show', as: 'products_show'

  get 'about' => 'products#about'

  post 'products/:id/reviews' => 'reviews#create', as: 'reviews'
  resources :reviews, only: [:destroy]

  post 'musics' => 'musics#create'
  get 'music' => 'master#new'


  post 'products/sort' => 'products#sort', as: 'products_sort'

  resources :users, only: [:show, :index, :edit, :update, :destroy]
  get 'users/:id/showorder' => 'users#showorder', as: 'showorder'

  resources :carts, only: [:index, :destroy, :update]
  get 'carts/create' => 'carts#create', as: 'carts_create'


  resources :favorites, only: [:index, :destroy]
  get 'favrites/create' => 'favorites#create', as: 'favorites_create'
  # resources :product_musics, only: [:edit, :destroy]
  # get 'products/:id/product_musics/new' => 'product_musics#new', as: 'new_product_music'
  # post 'products/:id/product_musics' => 'product_musics#create', as: 'product_musics'


  resources :orders, only: [:new, :create, :index, :destroy, :update]
  resources :destinations, only: [:create, :destroy,]

  # resources :order_products, only: [:create, :destroy,]


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :artist_name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, numericality: {less_than_or_equal_to: 9}
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :product
end

app/models/disc_music.rb
class DiscMusic < ApplicationRecord
  belongs_to :disc
  belongs_to :music
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genre_name, presence: true, uniqueness: true
end

app/models/label.rb
class Label < ApplicationRecord
	validates :label_name, presence: true, uniqueness: true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :artist
  validates :music_name, presence: true
  validates :artist_id, presence: true
  # music_nameとartist_idの組み合わせで一意でなくてはならない
  validates :music_name, :uniqueness => {:scope => :artist_id}
  has_many :prodcut_musics
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :scene
  belongs_to :genre
  belongs_to :label
  belongs_to :artist
  attachment :music_image
  has_many :carts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :carts
  has_many :product_musics, inverse_of: :product
  accepts_nested_attributes_for :product_musics, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/product_music.rb
class ProductMusic < ApplicationRecord
  belongs_to :product
  belongs_to :music
  validates :music_id, presence: :true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :title, presence: true
  validates :body, presence: true
end

app/models/scene.rb
class Scene < ApplicationRecord
	validates :scene_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # is_deletedがtrueのユーザはログインできないようにする
  def active_for_authentication?
    super && !is_deleted?
  end

# ここのメッセージが反映されない
  def inactive_message
    !is_deleted? ? super : :deleted_user
    # !is_deleted? super : :deleted_user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   attachment :profile_image


  # has_one :current_user_cart, -> {where(user_id: current_user.id)}, class_name: 'Cart'
  # has_one :current_cart, through: :current_user_cart, source: :product


  has_many :carts, dependent: :destroy
  has_many :products, through: :carts
  has_many :destinations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<div class="title">
		<h3>ユーザ一覧</h3>
</div>
<br>
<div class="col-md-8 col-md-offset-2">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>ユーザ名</th>
				<th>かな</th>
				<th>電話番号</th>
				<th>メールアドレス</th>
				<th>登録状況</th>
			</tr>
		</thead>

		<% @users.each do |user| %>
		<tbody>
			<tr class="active">
				<th><%= user.id %></th>
				<th><%= link_to user.user_name, admins_usershow_path(user), class: "user_name" %></th>
				<th><%= user.user_kana %></th>
				<th><%= user.phone_number %></th>
				<th><%= user.email %></th>
				<!-- 退会済みのユーザがわかるようにする -->
				<th><% if user.is_deleted == true %> 退会　<% end %></th>
			</tr>
		</tbody>
		<% end %>
	</table>

	<%= link_to "戻る", admins_top_path %>
</div>

<style>
	.table {
	background-color: #f5f5f5;
	border-radius: 10px;
	}
</style>

app/views/admins/productindex.html.erb
<div class="title">
	<h3>商品一覧ページ</h3>
</div>
<% @products.each do |product| %>
<div class="col-md-4 col-md-offset-1 index_area">
	<table class="table">
		<tbody>
			<%= attachment_image_tag product, :music_image,  format: 'jpeg', class: "music_image", fallback: "CD_NO_IMAGE.jpg", size: "150x150" %>

			<% if  product.is_deleted == true  %>
				<span class="sakujyo">削除済み</span>
			<% end %>

			<tr>
				<td>タイトル</td>
				<td><%= product.title.truncate(25) %></td>
			</tr>
			<tr>
				<td>アーティスト</td>
				<td><%= product.artist.artist_name %></td>
			</tr>
			<tr>
				<td>レーベル</td>
				<td><%= product.label.label_name %></td>
			</tr>
			<tr>
				<td>ジャンル</td>
				<td><%= product.genre.genre_name %></td>
			</tr>
			<tr>
				<td>価格</td>
				<td><%= product.price %></td>
			</tr>
			<tr>
				<td>在庫数</td>
				<td><%= product.stock %></td>
			</tr>
			<tr>
				<td><button type="button" class="btn btn-success btn-sm"><%=link_to "編集", product_path(product), class: "button" %></button></td>
				<td><button type="button" class="btn btn-danger btn-sm"><%= link_to "削除", admins_destroy_path(product), method: :delete, "data-confirm" => "本当に削除しますか？", class: "button" %></button></td>
			</tr>
		</tbody>
	</table>
</div>
<% end %>
<div class="col-md-5">
	<p><%= link_to "戻る", admins_top_path, class: "link" %></p>
</div>

<style>
.index_area {
	margin-left: 160px;
}
.sakujyo{
	background-color: black;
	color: white;
	margin-left: 100px;
	padding: 10px;
}
.music_image {
	margin-top: 10px;
	margin-bottom: 10px;
}
.link {
	margin-left: 160px;
}
.button {
	color: white;
}
.table {
	background-color: #f5f5f5;
	border-radius: 10px;
}
</style>

app/views/admins/top.html.erb
<% if flash[:notice] %>
       <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>
<div id="master-content">
	<br>
	<br>
	<%= link_to "商品登録", products_new_path, class: "master-content-link" %>
	<br>
	<br>
	<%= link_to "商品一覧", admins_products_path, class: "master-content-link" %>
	<br>
	<br>
	<%= link_to "ユーザ一覧", admins_path, class: "master-content-link" %>
	<br>
	<br>
	<%= link_to "マスタ登録", master_new_path, class: "master-content-link" %>
	<br>
	<br>
</div>


<style>
	#master-content{
		font-size: 26px;
		text-align: center;
		height: 400px;
		width: 400px;
		background-color: #f5f5f5;
		border-radius: 10px;
		margin: 0 auto;
	}

	.master-content-link{
		padding-bottom: 20px;
		color: black;
	}
</style>

app/views/admins/useredit.html.erb
<div class="title">
	<h3>ユーザ編集</h3>
</div>

<br>

<% if flash[:warning] %>
	<p class="alert alert-danger"><%= flash[:warning] %></p>
<% end %>

<%= form_for(@user,url: admins_userupdate_path) do |user| %>
	<div class="col-md-2 col-md-offset-2">
		<label>プロフィール画像</label>
		<%= attachment_image_tag @user, :profile_image,  format: 'jpeg', class: "", fallback: "no_image.jpg", size: "220x220" %>
		<br><br>
		<%= user.attachment_field :profile_image, class: "" %><br>
	</div>

	<div class="col-md-5 col-md-offset-1">
		<table class="table">
			<tbody>
				<tr>
					<td>ユーザ名</td>
					<td><%= user.text_field :user_name %></td>
				</tr>
				<tr>
					<td>かな</td>
					<td><%= user.text_field :user_kana %></td>
				</tr>
				<tr>
					<td>郵便番号</td>
					<td><%= user.text_field :zip_code %></td>
				</tr>
				<tr>
					<td>住所</td>
					<td><%= user.text_field :address %></td>
				</tr>
				<tr>
					<td>電話番号</td>
					<td><%= user.text_field :phone_number %></td>
				</tr>
			</tbody>
		</table>
		<%= user.submit "更新", class: "btn btn-default btn-sm" %>
		<br><br><br><br>
		<%= link_to "戻る", :back %>
	</div>
<% end %>

<style>
	.table {
		background-color: #f5f5f5;
		border-radius: 10px;
	}
</style>

app/views/admins/usershow.html.erb
<div class="title">
	<h3>ユーザ詳細</h3>
</div>
<br>
<% if flash[:notice] %>
	<p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>
<div class="profile col-md-offset-2">
<div class="col-md-3">
	<label>プロフィール画像</label>
	<%= attachment_image_tag @user, :profile_image,  format: 'jpeg', class: "", fallback: "no_image.jpg", size: "220x220" %>
</div>


<div class="col-md-5 col-md-offset-1">
	<table class="table">
		<tbody>
			<tr>
				<td>ユーザ名</td>
				<td><%= @user.user_name %></td>
			</tr>
			<tr>
				<td>かな</td>
				<td><%= @user.user_kana %></td>
			</tr>
			<tr>
				<td>郵便番号</td>
				<td><%= @user.zip_code %></td>
			</tr>
			<tr>
				<td>住所</td>
				<td><%= @user.address %></td>
			</tr>
			<tr>
				<td>電話番号</td>
				<td><%= @user.phone_number %></td>
			</tr>
		</tbody>
	</table>
	<%= link_to 'ユーザ情報編集', admins_useredit_path %>
	<br><br>
	<%= link_to '退会させる', admins_userdestroy_path ,method: :delete, "data-confirm" => '退会処理をしてよろしいですか？', class: "" %>
	<br><br>
	<%= link_to "戻る", admins_path %>
</div>
</div>


<div class="col-md-10">
	<br>
	<h4>購入履歴</h4>

	<div class="orders">
	<% @orders.each do |order| %>
	<!-- 注文ごとの合計金額変数 -->
	<% totalamount = 0 %>
	<!-- ８桁の番号になるように左から０埋め -->
	<div class="order-content">
		<div class="left-content">
		<p><strong>注文番号：<%= "%08d" % order.id %></strong></p>
		<!-- それぞれカラムの値によって表示を変更 -->
		<label>配送ステータス</label>
			<%= form_for order do |f|%>
				<%= f.select :status, [["受付中", "0"],["配送中", "1"],["配送済", "2"]],:selected=>order.status %>
				<%= f.submit '更新', class: "btn btn-default btn-sm" %>
			<% end %>
  			<br>
  			<br>
		<label>支払い方法</label>
		<% case order.pay
				when 0 %>
					<span class="pay status">代引き</span>
				<%when 1%>
  					<span class="pay status">クレジットカード</span>
  			<% end %>
  			<br>
  		</div>

  		<div class="right-content">
  			<!-- orderproductテーブルのレコード -->
  			<div class="">
  			<% @orderproducts.each do |product| %>
				<% if product.order_id == order.id %>
					<%= link_to products_show_path(product.product.id) do %>
					<div class="">
						<%= attachment_image_tag product.product, :music_image, class: "", fallback: "no_image.jpg", size: "100x100" %>
					</div>
					<% end %>
					<div class="">
					<%= link_to products_show_path(product.product.id) do %>
						<p><%= product.product.title %></p>
					<% end %>
					<p><%= product.price %>円</p>
					<p><%= product.quantity %>個</p>
					<p>小計：<%= sum = product.price * product.quantity %>円</p>
					</div>
					<% totalamount += sum %>
					<br>
					<br>

				<% end %>
			<% end %>
			<p id="amount">合計：<%= totalamount %>円</p>
			</div>
		</div>
		</div>
	<% end %>
</div>
</div>

<style>
	h4{
		padding-left: 250px;
		padding-top: 20px;
	}
	.orders{
		width: 100%;
		margin-top: 20px;
		margin-left: 20%;
	}

	.order-content{
		margin-bottom: 30px;
		padding: 20px;
		width: 80%;
		background-color: #f5f5f5;
		overflow: hidden;
	}


	.left-content{
		width: 30%;
		margin-right: 120px;
		float: left;
	}

	.right-content{
		float: left;
	}

	.status {
	display: inline-block;
	padding: 5px 5px;
	/*background-color: #ffc0cb;*/
	border-radius: 3px;
	color: #fff;
	font-size: 14px;
	}
	.pay{
		margin-left: 28px;
		background-color: gray;
	}

	#status1{
		background-color: #1e90ff;
	}

	#status2{
		background-color: green;
	}

	#status3{
		background-color: gray;
	}

	.table {
		background-color: #f5f5f5;
		border-radius: 10px;
	}

</style>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToYourHeart</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

</head>

<body>
  <div class="wrapper">
    <header>
      <nav class="navbar col-md-10">
        <ul class="" id="user_link">
          <!--サインインしていた場合  -->
          <% if admin_signed_in? %>
          <li id="user_name">
            <%= current_admin.email %>
            <span>ログイン中</span>
          </li>
          <li class="">
            <%= link_to destroy_user_session_path, method: :delete, class: "logout icons" do %>
            <i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>
            <span>ログアウト</span>
            <% end %>
          </li>

          <!--サインインしていなかった場合  -->
          <% else %>
          <li class="">
            <%= link_to user_session_path, class: "sign_in icons" do %>
            <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>
            <span>ログイン</span>
            <% end %>
          </li>
          <% end %>
        </ul>
      </nav>
    </header>

    <div class="main-content clearfix">
      <%= yield %>
    </div>

</div>
</body>
</html>


<style>
html {
  height: 100%;
}
body {
  min-height: 100%;
  display: flex;
  flex-direction: column;
}
.wrapper {
  flex: 1;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.clearfix::after {
  content: "";
  display: block;
  clear: both;
}


  header{
    height: 140px;
    width: 100%;
    background-color: #f8f8f8;
  }

  #sitelogo_img{
    text-align: right;
  }

  #user_name{
    padding: 15px;
  }

  #user_link{
    padding-top: 20px;
    font-size: 16px;
    height: 50px;
    width: 100%;
    text-align: right;
  }

  #user_link li{
    display: inline;
  }


  #site_link{
    height: 50px;
    width: 100%;
    text-align: center;
    margin-top: 20px;
    padding-left: 100px;
  }

  #site_link li{
    padding-left: 20px;
    padding-right: 20px;
    font-size: 17px;
    display: inline;
  }


  .main-content{
    margin-bottom: 50px;
    /*height: 1000px;*/
  }

  .title{
  width: 80%;
    padding: 0.5em 1em;
    margin: 0 10%;
    color: black;
    background: white;
    border-bottom: solid 10px black;
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToYourHeart</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>

  <link href="https://fonts.googleapis.com/css?family=Kosugi+Maru" rel="stylesheet">
  <link href="select2.min.css" rel="stylesheet" />

  <%= javascript_include_tag 'application' %>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  <script src="select2.min.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>

<body>
  <div class="wrapper">
    <header>
      <!-- adminでサインインしていた場合は管理者用ヘッダ -->
      <% if admin_signed_in? %>
      <nav class="col-md-2" id="sitelogo" style="text-align:center"><%= image_tag 'sitelogo.png', :size =>'160x100' %></nav>
      <div id="adminheader">
        <%= current_admin.email %><span>ログイン中</span>
        <br>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "" %>
      </div>
      <!-- adminでサインインしてない場合の処理 -->
      <% else %>
      <!-- ロゴをクリックしてもHOMEと同じ動きをするようにする必要あり -->
      <nav class="col-md-2" id="sitelogo" style="text-align:center">
        <%= link_to products_path do %>
          <%= image_tag 'sitelogo.png', :size =>'160x100' %>
        <% end %>
      </nav>

      <nav class="navbar col-md-10">
        <ul class="" id="user_link">

          <!--サインインしていた場合  -->
          <% if user_signed_in? %>
          <li id="user_name">
            <%= current_user.user_name %>
            <span> 様   </span>
            <span>ログイン中</span>
          </li>

          <li class="">
            <%= link_to user_path(current_user.id), class: "icons mypage" do %>
            <i class="glyphicon glyphicon-home" aria-hidden="true" style="color:black"></i>
            <span class="links">マイページ</span>

            <% end %>
          </li>
          <li class="">
            <%= link_to carts_path, class: "icons cart" do %>
            <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true" style="color:black"></i>
            <span class="links">カート</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to favorites_path, class: "favorite icons" do %>
            <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color:black"></i>
            <span class="links">お気に入り</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to destroy_user_session_path, method: :delete, class: "logout icons" do %>
            <i class="glyphicon glyphicon-log-out" aria-hidden="true" style="color:black"></i>
            <span class="links">ログアウト</span>
            <% end %>
          </li>

          <!--サインインしていなかった場合  -->
          <% else %>
          <li class="">
            <%= link_to new_user_registration_path, class: "sign_up icons" do %>
            <i class="glyphicon glyphicon-user" aria-hidden="true" style="color:black"></i>
            <span class="links">新規ユーザ登録</span>
            <% end %>
          </li>
          <li class="">
            <%= link_to user_session_path, class: "sign_in icons" do %>
            <i class="glyphicon glyphicon-log-in" aria-hidden="true" style="color:black"></i>
            <span class="links">ログイン</span>
            <% end %>
          </li>
          <% end %>
        </ul>


        <ul class="navbar-nav" id="site_link">
          <li><%= link_to "トップページ", products_path, class: "links" %></li>
          <li><%= link_to "当サイトについて", about_path, class: "links" %></li>
          <li><a href="#footer" class="links">アクセス</a></li>
          <li><%= link_to "お問い合わせ", contact_path, class: "links" %></li>

        </ul>
        <% end %>
      </nav>
    </header>

    <div class="main-content clearfix">
      <%= yield %>
    </div>
  </div>

    <footer id="footer">
      <div class="container">
          <div class="">
            <h3>アクセス</h3>
            <p>〒390-0221</p>
            <p>長野県○○市X-XX-X</p>
          </div>
           <p class="footer_logo">CopyRight Infratop.inc</p>
        </div>
    </footer>
</body>
</html>


<style>
html {
  height: 100%;
}
body {
  min-height: 100%;
  display: flex;
  flex-direction: column;
}
.wrapper {
  flex: 1;
  background: rgba(255,255,255,0.4);
}

.footer_logo{
  float: right;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.clearfix::after {
  content: "";
  display: block;
  clear: both;
}


header{
  height: 140px;
  width: 100%;
}

#adminheader{
  font-size: 16px;
  padding-top: 80px;
  padding-right: 30px;
  text-align: right;
}

.links {
  color: black;
}

#sitelogo_img{
  text-align: right;
}

#user_name{
  padding: 15px;
}

#user_link{
  padding-top: 20px;
  font-size: 16px;
  height: 50px;
  width: 100%;
  text-align: right;
}

#user_link li{
  display: inline;
}


#site_link{
  height: 50px;
  width: 100%;
  text-align: center;
  margin-top: 20px;
  padding-left: 200px;
}

#site_link li{
  padding-left: 20px;
  padding-right: 20px;
  font-size: 17px;
  display: inline;
}


.main-content{
  margin-bottom: 50px;
  /*height: 1000px;*/
}

.icons{
  padding-right: 30px;
  /*margin-right: 30px;*/
  /*margin-left: 30px;*/
}
.title{
  width: 80%;
  padding: 0.5em 1em;
  margin: 0 10%;
  color: black;
  border-bottom: solid 10px black;
}

footer{
  bottom: 0;
  height: 250px;
  background-color: black;
  color:white;
}

</style>