config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  devise_for :admins
  get 'master/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products' => 'products#index'
  root 'products#index'

  get 'admins/top'
  get 'admins/products' => 'admins#productindex'
  delete 'admins/products/:id' => 'admins#productdestroy', as: 'admins_destroy'


  get 'admins' => 'admins#index'
  get 'admins/:id' => 'admins#usershow', as: 'admins_usershow'
  patch 'admins/:id' => 'admins#userupdate', as: 'admins_userupdate'
  get 'admins/:id/edit' => 'admins#useredit', as: 'admins_useredit'
  delete 'admins/:id/destroy' => 'admins#userdestroy', as: 'admins_userdestroy'

  post 'artists' => 'artists#create'
  get 'artist' => 'master#new'

  post 'genres' => 'genres#create'
  get 'genre' => 'master#new'

  post 'labels' => 'labels#create'
  get 'label' => 'master#new'

  post 'scenes' => 'scenes#create'
  get 'scene' => 'master#new'

  get 'contact' => 'products#contact'
  
  get 'products/new' => 'products#new'
  post 'products' => 'products#create'

  get 'products/:id/edit' => 'products#edit', as: 'product'
  # post 'products' => 'products#update'
  patch '/products/:id' => 'products#update', as: 'update_product'
  get 'products/:id' => 'products#show', as: 'products_show'

  get 'about' => 'products#about'

  post 'products/:id/reviews' => 'reviews#create', as: 'reviews'
  resources :reviews, only: [:destroy]

  post 'musics' => 'musics#create'
  get 'music' => 'master#new'


  post 'products/sort' => 'products#sort', as: 'products_sort'

  resources :users, only: [:show, :index, :edit, :update, :destroy]
  get 'users/:id/showorder' => 'users#showorder', as: 'showorder'

  resources :carts, only: [:index, :destroy, :update]
  get 'carts/create' => 'carts#create', as: 'carts_create'


  resources :favorites, only: [:index, :destroy]
  get 'favrites/create' => 'favorites#create', as: 'favorites_create'
  # resources :product_musics, only: [:edit, :destroy]
  # get 'products/:id/product_musics/new' => 'product_musics#new', as: 'new_product_music'
  # post 'products/:id/product_musics' => 'product_musics#create', as: 'product_musics'


  resources :orders, only: [:new, :create, :index, :destroy, :update]
  resources :destinations, only: [:create, :destroy,]

  # resources :order_products, only: [:create, :destroy,]


end

app/models/user.rb
class User < ApplicationRecord
  # is_deletedがtrueのユーザはログインできないようにする
  def active_for_authentication?
    super && !is_deleted?
  end

# ここのメッセージが反映されない
  def inactive_message
    !is_deleted? ? super : :deleted_user
    # !is_deleted? super : :deleted_user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   attachment :profile_image


  # has_one :current_user_cart, -> {where(user_id: current_user.id)}, class_name: 'Cart'
  # has_one :current_cart, through: :current_user_cart, source: :product


  has_many :carts, dependent: :destroy
  has_many :products, through: :carts
  has_many :destinations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		# 退会したユーザは表示させない処理を追加する
		@users = User.all
	end

	#ユーザのマイページ用に作成。管理者からの機能は後ほど追加。
	def show
	  	
	  	@user = User.find(params[:id])

  	end

	def showorder
	  	@user = User.find(params[:id])
	  	@orders = Order.where(user_id: @user.id).reverse_order
		@orderproducts = OrderProduct.all
  	end

    def edit
    	@user = User.find(params[:id])

    end

    def update

    	user = User.find(params[:id])
	  	if user.update(user_params)
	      flash[:notice] = 'ユーザ情報が更新されました。'
	      redirect_to user_path(user.id)
	    else
	      flash[:warning] = 'ユーザ情報の更新に失敗しました。'
	      redirect_to edit_user_path(user.id)
    	end
    end

    # 退会処理　論理削除
    def destroy
    	user = User.find(params[:id])
    	user.is_deleted = true
    	user.save
    	# ログアウトさせる(現在不具合あり)
    	redirect_to destroy_user_session_path
    end


    private

	def user_params
		params.require(:user).permit(:user_name, :user_kana, :zip_code, :address, :phone_number, :profile_image)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="title">
	<h3>ユーザ情報更新ページ</h3>
</div>
<br>
<br>
<% if flash[:warning] %>
       <p class="alert alert-danger"><%= flash[:warning] %></p>
<% end %>

<div class="col-md-offset-2">
<%= form_for(@user) do |user| %>
	<div class="col-md-3">
		<label>プロフィール画像</label>
		<%= attachment_image_tag @user, :profile_image,  format: 'jpeg', class: "", fallback: "no_image.jpg", size: "220x220" %>
		<br><br>
		<%= user.attachment_field :profile_image, class: "" %><br>
	</div>
	<br>
	<br>
	<div class="col-md-5 col-md-offset-1">
		<table class="table">
			<tbody>
				<tr>
					<td>ユーザ名</td>
					<td><%= user.text_field :user_name %></td>
				</tr>
				<tr>
					<td>かな</td>
					<td><%= user.text_field :user_kana %></td>
				</tr>
				<tr>
					<td>郵便番号</td>
					<td><%= user.text_field :zip_code %></td>
				</tr>
				<tr>
					<td>住所</td>
					<td><%= user.text_field :address %></td>
				</tr>
				<tr>
					<td>電話番号</td>
					<td><%= user.text_field :phone_number %></td>
				</tr>
			</tbody>
		</table>
			<%= user.submit "更新", class: "btn btn-primary" %>
		</div>
</div>

<% end %>

<style>
	.btn-primary{
		padding: 5px;
		text-align: right;
	}
	.table {
	background-color: #f5f5f5;
	border-radius: 10px;
	}
</style>

app/views/users/show.html.erb
<div class="title">
	<h3>マイページ</h3>
</div>

<% if flash[:notice] %>
       <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>

<br>
<br>

<div class="profile col-md-offset-2">
	<div class="col-md-3">
		<label>プロフィール画像</label>
		<%= attachment_image_tag @user, :profile_image,  format: 'jpeg', class: "", fallback: "no_image.jpg", size: "220x220" %>
	</div>

	<br>
	<br>
	<div class="col-md-5 col-md-offset-1">
		<table class="table">
			<tbody>
				<tr>
					<td>ユーザ名</td>
					<td><%= @user.user_name %></td>
				</tr>
				<tr>
					<td>かな</td>
					<td><%= @user.user_kana %></td>
				</tr>
				<tr>
					<td>郵便番号</td>
					<td><%= @user.zip_code %></td>
				</tr>
				<tr>
					<td>住所</td>
					<td><%= @user.address %></td>
				</tr>
				<tr>
					<td>電話番号</td>
					<td><%= @user.phone_number %></td>
				</tr>
			</tbody>
		</table>
		<%= link_to 'ユーザ情報変更', edit_user_path(current_user.id) %><br><br>
		<%= link_to '注文履歴一覧', showorder_path %><br><br>
		<%= link_to '退会する', user_path(current_user.id) ,method: :delete, "data-confirm" => '退会してよろしいですか？' %>

	</div>
</div>



<style>
	h1{
		text-align: center;
	}

	.title{
	width: 80%;
    padding: 0.5em 1em;
    margin: 0 10%;
    color: black;
    /*background: white;*/
    border-bottom: solid 10px black;
	}
	.link{
		margin-top: 100px;
	}
	.profile{
		margin-bottom: 50px;
	}
	.table {
	background-color: #f5f5f5;
	border-radius: 10px;
	}
</style>

app/views/users/showorder.html.erb
<div class="title">
	<h3>購入履歴</h3>
</div>
<% if flash[:notice] %>
       <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>
<br>
<% if @orders.length == 0 %>
	<h4>購入履歴はありません</h4>
<% end %>

<div class="orders">
	<% @orders.each do |order| %>
	<!-- 注文ごとの合計金額変数 -->
	<% totalamount = 0 %>
	<!-- ８桁の番号になるように左から０埋め -->
	<div class="order-content">
		<p style="border-bottom: solid 3px"><strong>購入日：<%= order.created_at.strftime('%Y/%m/%d') %></strong></p>
		<div class="left-content">
		<p><strong>注文番号：<%= "%08d" % order.id %></strong></p>
		<!-- それぞれカラムの値によって表示を変更 -->
		<label>配送ステータス</label>

			<% case order.status
				when 0 %>
					<span id="status1" class="status">受付中</span>
				<%when 1%>
  					<span id="status2" class="status">配送中</span>
  				<%when 2%>
  					<span id="status3" class="status">配送済</span>
  			<% end %>
  			<br>
  			<br>
		<label>支払い方法</label>
		<% case order.pay
				when 0 %>
					<span class="pay status">代引き</span>
				<%when 1%>
  					<span class="pay status">クレジットカード</span>
  		<% end %>
  		<br>
  		<br>
  		<% if order.status == 0 %>
  			<%= link_to '注文キャンセル', order_path, method: :delete, "data-confirm" => '注文をキャンセルしてよろしいですか？', class: "btn btn-warning" %>
  		<% end %>
  			<br><br><br><br>
  			<label style="border-bottom: solid 3px">配送先</label><br>
  			<label>宛名：<%= order.destination.friend_name %></label><br>
  			<label>〒<%= order.destination.zip_code %></label><br>
  			<label><%= order.destination.address %></label>

  		</div>


  		<div class="right-content ">
  			<!-- orderproductテーブルのレコード -->
  			<% @orderproducts.each do |product| %>
				<% if product.order_id == order.id %>
					<div class="product-img">
					<%= link_to products_show_path(product.product.id) do %>
						<%= attachment_image_tag product.product, :music_image, class: "", fallback: "no_image.jpg", size: "120x120" %>
					<% end %>
					</div>

					<div class="product-text">
					<%= link_to products_show_path(product.product.id) do %>
						<p><%= product.product.title %></p>
					<% end %>
					<p><%= product.price %>円</p>
					<p><%= product.quantity %>個</p>
					<p>小計：<%= sum = product.price * product.quantity %>円</p>
					</div>
					<% totalamount += sum %>
					<br>
					<br>

				<% end %>
			<% end %>
			<p id="amount">合計：<%= totalamount %>円</p>
			</div>
		</div>
	<% end %>
</div>



<style>
	h4{
		margin-top: 50px;
		text-align: center
	}

	.orders{
		margin-top: 70px;
		margin-left: 20%;
	}

	.order-content{
		/*overflow: hidden;*/
		position: relative;
		margin-bottom: 30px;
		padding: 20px;
		width: 80%;
		background-color: #f5f5f5;
		overflow: hidden;
	}


	.title{
		width: 80%;
	    padding: 0.5em 1em;
	    margin: 0 10%;
	    color: black;
	    /*background: white;*/
	    border-bottom: solid 10px black;
	}

	.left-content{
		width: 30%;
		margin-top: 20px;
		margin-left: 20px;
		margin-right: 60px;
		float: left;
	}

	.right-content{
		/*overflow: hidden;*/
		margin-top: 20px;
		float: left;
	}

	.product-img{
		margin-right: 20px;
		margin-bottom: 20px;
		float: left;
	}

	.product-text{
		padding-top: 5px;
		margin-bottom: 20px;
		float: left;
	}

	.status {
		display: inline-block;
		padding: 5px 5px;
		border-radius: 3px;
		color: #fff;
		font-size: 14px;
	}

	.pay{
		margin-left: 28px;
		background-color: gray;
	}

	#status1{
		background-color: #1e90ff;
	}

	#status2{
		background-color: green;
	}

	#status3{
		background-color: gray;
	}

	#amount{
		position: absolute;
		right: 50px;
		bottom: 0px;
	}
</style>