config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  devise_for :admins
  get 'master/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products' => 'products#index'
  root 'products#index'

  get 'admins/top'
  get 'admins/products' => 'admins#productindex'
  delete 'admins/products/:id' => 'admins#productdestroy', as: 'admins_destroy'


  get 'admins' => 'admins#index'
  get 'admins/:id' => 'admins#usershow', as: 'admins_usershow'
  patch 'admins/:id' => 'admins#userupdate', as: 'admins_userupdate'
  get 'admins/:id/edit' => 'admins#useredit', as: 'admins_useredit'
  delete 'admins/:id/destroy' => 'admins#userdestroy', as: 'admins_userdestroy'

  post 'artists' => 'artists#create'
  get 'artist' => 'master#new'

  post 'genres' => 'genres#create'
  get 'genre' => 'master#new'

  post 'labels' => 'labels#create'
  get 'label' => 'master#new'

  post 'scenes' => 'scenes#create'
  get 'scene' => 'master#new'

  get 'contact' => 'products#contact'
  
  get 'products/new' => 'products#new'
  post 'products' => 'products#create'

  get 'products/:id/edit' => 'products#edit', as: 'product'
  # post 'products' => 'products#update'
  patch '/products/:id' => 'products#update', as: 'update_product'
  get 'products/:id' => 'products#show', as: 'products_show'

  get 'about' => 'products#about'

  post 'products/:id/reviews' => 'reviews#create', as: 'reviews'
  resources :reviews, only: [:destroy]

  post 'musics' => 'musics#create'
  get 'music' => 'master#new'


  post 'products/sort' => 'products#sort', as: 'products_sort'

  resources :users, only: [:show, :index, :edit, :update, :destroy]
  get 'users/:id/showorder' => 'users#showorder', as: 'showorder'

  resources :carts, only: [:index, :destroy, :update]
  get 'carts/create' => 'carts#create', as: 'carts_create'


  resources :favorites, only: [:index, :destroy]
  get 'favrites/create' => 'favorites#create', as: 'favorites_create'
  # resources :product_musics, only: [:edit, :destroy]
  # get 'products/:id/product_musics/new' => 'product_musics#new', as: 'new_product_music'
  # post 'products/:id/product_musics' => 'product_musics#create', as: 'product_musics'


  resources :orders, only: [:new, :create, :index, :destroy, :update]
  resources :destinations, only: [:create, :destroy,]

  # resources :order_products, only: [:create, :destroy,]


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :artist_name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, numericality: {less_than_or_equal_to: 9}
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :product
end

app/models/disc_music.rb
class DiscMusic < ApplicationRecord
  belongs_to :disc
  belongs_to :music
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genre_name, presence: true, uniqueness: true
end

app/models/label.rb
class Label < ApplicationRecord
	validates :label_name, presence: true, uniqueness: true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :artist
  validates :music_name, presence: true
  validates :artist_id, presence: true
  # music_nameとartist_idの組み合わせで一意でなくてはならない
  validates :music_name, :uniqueness => {:scope => :artist_id}
  has_many :prodcut_musics
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :scene
  belongs_to :genre
  belongs_to :label
  belongs_to :artist
  attachment :music_image
  has_many :carts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :carts
  has_many :product_musics, inverse_of: :product
  accepts_nested_attributes_for :product_musics, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/product_music.rb
class ProductMusic < ApplicationRecord
  belongs_to :product
  belongs_to :music
  validates :music_id, presence: :true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :title, presence: true
  validates :body, presence: true
end

app/models/scene.rb
class Scene < ApplicationRecord
	validates :scene_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # is_deletedがtrueのユーザはログインできないようにする
  def active_for_authentication?
    super && !is_deleted?
  end

# ここのメッセージが反映されない
  def inactive_message
    !is_deleted? ? super : :deleted_user
    # !is_deleted? super : :deleted_user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   attachment :profile_image


  # has_one :current_user_cart, -> {where(user_id: current_user.id)}, class_name: 'Cart'
  # has_one :current_cart, through: :current_user_cart, source: :product


  has_many :carts, dependent: :destroy
  has_many :products, through: :carts
  has_many :destinations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  	# 現在ログイン中のユーザのカート内表示
  	@products = current_user.products
  end

  # カートに商品を追加
  def create
  	cart = Cart.new
  	user = current_user

  	# user_idはcurrent_userのidを代入
  	cart.user_id = current_user.id
  	#product_idはクリックされた商品のproduct_idを代入
  	cart.product = Product.find(params[:product_id])

  	# カート内にuser, productの組み合わせを検索して変数へ代入
  	added_cart = user.carts.find_by(product_id: cart.product.id)
  	# 存在しなければ新たにカートに追加
  	if  added_cart == nil
  		cart.save
  	# 存在する場合は、quantityを＋１する
  	else
  		added_cart.quantity += 1
  		added_cart.save
  	end
  end

# カート内の商品を削除するアクション
  def destroy
  	# 削除したい商品を特定
  	user = current_user
  	product = Product.find(params[:id])
  	# cartsテーブル内で削除するカラムを指定(１件取得のためfind_by)
  	cart = user.carts.find_by(product_id: product.id)
	if cart.destroy
		flash[:notice] = "カート内商品を１件削除しました。"
		redirect_to carts_path
	end
  end

# 個数変更
  def update
	cart =  Cart.find(params[:id])
	cart.update(cart_params)
	flash[:notice] = "個数を変更しました。"
	redirect_to carts_path
  end

  # private
  def cart_params
	params.require(:cart).permit(:quantity)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/create.js.erb
// アクション時にアニメーションをつけるならここに記述

app/views/carts/index.html.erb
<!-- ログイン中のユーザのカート内一覧を表示 -->

	<div class="title">
	<h3>カート内商品</h3>
	</div>
	<br>
	<% if flash[:notice] %>
	<p class="alert alert-success"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:warning] %>
	<p class="alert alert-success"><%= flash[:warning] %></p>
	<% end %>

	<% if @products.length == 0 %>
	<div class="orderlink col-md-12">
	<h4>カート内に商品はありません</h4><br><br><br><br>
	<%= link_to '注文履歴一覧へ', showorder_path(current_user), class: "orderlink" %>
	</div>
	<% end %>

<div class="cart col-md-offset-2">
	<% @products.each do |product| %>
	<div class="cart-content col-md-8 col-md-offset-1">
		<div class="col-md-3">
			<%= attachment_image_tag product, :music_image, class: "", fallback: "CD_NO_IMAGE.jpg", size: "200x200" %>
		</div>

		<div class="product-status col-md-4 col-md-offset-1">
			<p><%= product.title %></p>
			<p><%= product.artist.artist_name %></p>
			<p><%= product.price %> 円</p>
			<p>在庫数：<%= product.stock %> 個</p>
		</div>
		<!-- 該当する商品の注文個数をDBから引っ張る -->
		<% quantity = product.carts.find_by(user_id: current_user.id).quantity %>

		<!-- 個数の選択タブ　デフォルトの値をquantityにする -->
		<% @cart = product.carts.find_by(user_id: current_user.id) %>
		<div class="product-status col-md-3">
			<%= form_for(@cart) do |f| %>
				<%= f.select :quantity, [[1,1], [2,2], [3,3], [4,4], [5,5], [6,6], [7,7], [8,8], [9,9]] ,:selected => quantity %>
				<!-- 個数更新ボタン　個数変更後にクリックすることでDB更新、画面更新する -->
				<%= f.submit '更新', class: "cart_update btn btn-default" %>
			<% end %>

			<!-- 選択済みのタブの個数をかけて非同期で金額を変えられるのがベスト -->
			<p class="subtotal">小計：<%= product.price * quantity %> 円</p>
		</div>
			<%= link_to '削除', cart_path(product), :method => :delete, data: { confirm: '削除しますか？' } , class: "cart_delete btn btn-default col-md-1" %>
	</div>
	<% end %>
</div>

<div class="orderbtn col-md-12">
	<!--会計処理リンクはカート内に商品があるときのみ表示  -->
	<% if @products.length != 0 %>
	<%= link_to '会計へ進む',new_order_path , class: "neworderbtn btn btn-default" %>
	<br><br><br>
	<%= link_to '注文履歴一覧へ', showorder_path(current_user), class: "orderlink" %>
	<% end %>
</div>

<style >
h4{
	margin-top: 100px;
	text-align: center;
}

.title{
	width: 80%;
    padding: 0.5em 1em;
    margin: 0 10%;
    color: black;
    /*background: white;*/
    border-bottom: solid 10px black;
}

.orderlink{
	text-align: center;
	font-size: 16px;
	/*color: black;*/
}
.space{
	height: 200px;
}

.cart-content{
	margin-top: 10px;
	margin-bottom: 10px;
	background-color: #f5f5f5;
	border-radius: 10px;
	padding: 30px 20px;
}
.product-status{
	font-size: 16px;
	height: 200px;
	padding-top: 10px;
}
.product-status p{
	margin-bottom: 30px;
}

.subtotal{
	/*float: left;*/
}

.cart_update{
	margin-top: 15px;
	margin-bottom: 20px;
}

.cart_delete{
	margin-top: 90px;
}

.orderbtn{
	margin-top: 50px;
	text-align: center;
}

.neworderbtn{
	width: 40%;
}
</style>