config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  devise_for :admins
  get 'master/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products' => 'products#index'
  root 'products#index'

  get 'admins/top'
  get 'admins/products' => 'admins#productindex'
  delete 'admins/products/:id' => 'admins#productdestroy', as: 'admins_destroy'


  get 'admins' => 'admins#index'
  get 'admins/:id' => 'admins#usershow', as: 'admins_usershow'
  patch 'admins/:id' => 'admins#userupdate', as: 'admins_userupdate'
  get 'admins/:id/edit' => 'admins#useredit', as: 'admins_useredit'
  delete 'admins/:id/destroy' => 'admins#userdestroy', as: 'admins_userdestroy'

  post 'artists' => 'artists#create'
  get 'artist' => 'master#new'

  post 'genres' => 'genres#create'
  get 'genre' => 'master#new'

  post 'labels' => 'labels#create'
  get 'label' => 'master#new'

  post 'scenes' => 'scenes#create'
  get 'scene' => 'master#new'

  get 'contact' => 'products#contact'
  
  get 'products/new' => 'products#new'
  post 'products' => 'products#create'

  get 'products/:id/edit' => 'products#edit', as: 'product'
  # post 'products' => 'products#update'
  patch '/products/:id' => 'products#update', as: 'update_product'
  get 'products/:id' => 'products#show', as: 'products_show'

  get 'about' => 'products#about'

  post 'products/:id/reviews' => 'reviews#create', as: 'reviews'
  resources :reviews, only: [:destroy]

  post 'musics' => 'musics#create'
  get 'music' => 'master#new'


  post 'products/sort' => 'products#sort', as: 'products_sort'

  resources :users, only: [:show, :index, :edit, :update, :destroy]
  get 'users/:id/showorder' => 'users#showorder', as: 'showorder'

  resources :carts, only: [:index, :destroy, :update]
  get 'carts/create' => 'carts#create', as: 'carts_create'


  resources :favorites, only: [:index, :destroy]
  get 'favrites/create' => 'favorites#create', as: 'favorites_create'
  # resources :product_musics, only: [:edit, :destroy]
  # get 'products/:id/product_musics/new' => 'product_musics#new', as: 'new_product_music'
  # post 'products/:id/product_musics' => 'product_musics#create', as: 'product_musics'


  resources :orders, only: [:new, :create, :index, :destroy, :update]
  resources :destinations, only: [:create, :destroy,]

  # resources :order_products, only: [:create, :destroy,]


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/artist.rb
class Artist < ApplicationRecord
	validates :artist_name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, numericality: {less_than_or_equal_to: 9}
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :product
end

app/models/disc_music.rb
class DiscMusic < ApplicationRecord
  belongs_to :disc
  belongs_to :music
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genre_name, presence: true, uniqueness: true
end

app/models/label.rb
class Label < ApplicationRecord
	validates :label_name, presence: true, uniqueness: true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :artist
  validates :music_name, presence: true
  validates :artist_id, presence: true
  # music_nameとartist_idの組み合わせで一意でなくてはならない
  validates :music_name, :uniqueness => {:scope => :artist_id}
  has_many :prodcut_musics
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :scene
  belongs_to :genre
  belongs_to :label
  belongs_to :artist
  attachment :music_image
  has_many :carts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :carts
  has_many :product_musics, inverse_of: :product
  accepts_nested_attributes_for :product_musics, reject_if: :all_blank, allow_destroy: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/product_music.rb
class ProductMusic < ApplicationRecord
  belongs_to :product
  belongs_to :music
  validates :music_id, presence: :true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :title, presence: true
  validates :body, presence: true
end

app/models/scene.rb
class Scene < ApplicationRecord
	validates :scene_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # is_deletedがtrueのユーザはログインできないようにする
  def active_for_authentication?
    super && !is_deleted?
  end

# ここのメッセージが反映されない
  def inactive_message
    !is_deleted? ? super : :deleted_user
    # !is_deleted? super : :deleted_user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   attachment :profile_image


  # has_one :current_user_cart, -> {where(user_id: current_user.id)}, class_name: 'Cart'
  # has_one :current_cart, through: :current_user_cart, source: :product


  has_many :carts, dependent: :destroy
  has_many :products, through: :carts
  has_many :destinations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update]
	def index
  	# config/initializers/kaminari_configで1ページの表示件数20件に設定
    # @slideproducts = Product.page(params[:page]).reverse_order

    @slideproducts = Product.limit(20).order('release_date DESC')

    # @products = Product.page(params[:page]).reverse_order

    @search = Product.ransack(params[:q])
    @result = @search.result.page(params[:page]).reverse_order

  end

    def sort
        sortValue = params["sortValue"]

        if sortValue == "price_desc"
            products = Product.all.order(price: "DESC")
        elsif sortValue == "price_asc"
            products = Product.all.order(price: "ASC")
        elsif sortValue == "review_score"
            products = Product.all.includes(:review).order("reviews.score desc")
        else
            products = Product.page(params[:page]).reverse_order
        end

        render json: products
    end

    def show
        @product = Product.find(params[:id])
        @review = Review.new
    end

	def new
		@product = Product.new
    @product.product_musics.build
    @artists = Artist.all.order(:artist_kana)
	end

	def create
		 # ストロングパラメーターを使用
    product = Product.new(product_params)
    # DBへ保存する
    if product.save!
     	flash[:notice] = "商品が1件登録されました。"
     	redirect_to products_new_path
    else
     	flash[:warning] = "商品の登録に失敗しました。。"
     	redirect_to products_new_path
    end
	end

  def edit
        @product = Product.find(params[:id])
         @artists = Artist.all.order(:artist_kana)
  end

  def update
    product = Product.find(params[:id])
    if product.update(update_product_params)
      flash[:notice] = '商品情報が更新されました。'
      redirect_to product_path(product.id)
    else
      flash[:warning] = '商品情報の更新に失敗しました。'
      redirect_to product_path(product.id)
    end
  end

  def about
  end


    def contact
      
    end

	 private

    def product_params
      params.require(:product).permit(:music_image, :title, :kana, :price, :label_id, :genre_id, :scene_id, :release_date,
        :stock, :artist_id, product_musics_attributes: [:disc_num, :track_num, :music_id])
    end

    def update_product_params
      params.require(:product).permit(:music_image, :title, :kana, :price, :label_id, :genre_id, :scene_id, :release_date,
        :stock,:artist_id, product_musics_attributes: [:disc_num, :track_num, :music_id, :id, :_destroy])
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_editproduct_music_fields.html.erb
<div class='nested-fields'>
	<!-- <div id="editproduct_musics_body"> -->
		<table class="table">
			<thead>
				<tr>
					<th><label>ディスク番号</label></th>
	                <th><label>トラック番号</label></th>
	                <th><label>収録曲名</label></th>
	                <th></th>
	            </tr>
	        </thead>
	        <tbody>
	            <tr>
					<td>
						<%= f.select :disc_num, [[1,1],[2,2],[3,3],[4,4],[5,5],[6,6,],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15]] %>
					</td>
					<td>
						<%= f.select :track_num, [[1,1],[2,2],[3,3],[4,4],[5,5],[6,6,],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15]] %>
					</td>
					<td>
						<%= f.collection_select :music_id, Music.all, :id, :music_name, :include_blank => true %>
					</td>
					<td>
						<%= link_to_remove_association '削除', f, class: "btn btn-default btn-sm" %>
					</td>
				</tr>
			</tbody>
		</table>
	<!-- </div> -->
</div>

<style>
	.table {
		background-color: #f5f5f5;
		border-radius: 10px;
	}
</style>

app/views/products/_product_music_fields.html.erb
<div class='nested-fields'>
	<div id="product_musics_body">
		<table class="table">
			<thead>
				<tr>
					<th><label>ディスク番号</label></th>
	                <th><label>トラック番号</label></th>
	                <th><label>収録曲名</label></th>
	                <th></th>
	            </tr>
	        </thead>
	        <tbody>
	            <tr>
					<td>
						<%= f.select :disc_num, [[1,1],[2,2],[3,3],[4,4],[5,5],[6,6,],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15]] %>
					</td>
					<td>
						<%= f.select :track_num, [[1,1],[2,2],[3,3],[4,4],[5,5],[6,6,],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12],[13,13],[14,14],[15,15]] %>
					</td>
					<td>
						<%= f.select :music_id, options_from_collection_for_select(Music.all, :id, :music_name), {include_blank: true}, class: "searchable" %>
					</td>
					<td>
						<%= link_to_remove_association '削除', f, class: "btn btn-default btn-sm" %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<script>
    $(document).ready(function() {
    $('.searchable').select2();
});
</script>

<style>
	.table {
		background-color: #f5f5f5;
		border-radius: 10px;
	}
</style>

app/views/products/about.html.erb
<div class="title">
    <h3>当サイトについて</h3>
</div>

app/views/products/contact.html.erb
<div class="title">
    <h3>お問い合わせフォーム</h3>
</div>

	<div id="contact">
	    <form action="contact" method="get">
			<p><label>名前：</label><br><input type="text" name="name" size="40"><br></p><br>
			<p><label>本文：<br><textarea name="comments" rows="2" cols="40"></textarea></label></p>
			<p><input type="submit" value="送信" class="btn btn-default"></p>
		</form>
	</div>


<style>
	#contact{
		margin-top: 100px;
		margin-left: 20%;
		margin-bottom: 100px;
	}
	textarea{
		height: 150px;
		width: 400px;
	}
</style>

app/views/products/edit.html.erb
<h1>商品編集ページ</h1>
<br>
<br>
<% if flash[:warning] %>
<p class="alert alert-danger"><%= flash[:warning] %></p>
<% end %>
<% if flash[:notice] %>
<p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>

<div class="col-md-offset-2 col-md-10">
	<%= form_for(@product, url: update_product_path) do |product| %>
	<div class="col-md-4">
		<%= attachment_image_tag @product, :music_image,  format: 'jpeg', class: "", fallback: "CD_NO_IMAGE.jpg", size: "200x200" %>
		<%= product.attachment_field :music_image, class: "" %><br>

		<!-- <div class="col-md-5"> -->
		<table class="table">
			<tbody>
				<tr>
					<td>商品名</td>
					<td><%= product.text_field :title %></td>
				</tr>
				<tr>
					<td>値段</td>
					<td><%= product.text_field :price %></td>
				</tr>
				<tr>
					<td>アーティスト</td>
					<td><%= product.collection_select :artist_id, Artist.all, :id, :artist_name %></td>
				</tr>
				<tr>
					<td>レーベル</td>
					<td><%= product.collection_select :label_id, Label.all, :id, :label_name %></td>
				</tr>
				<tr>
					<td>ジャンル</td>
					<td><%= product.collection_select :genre_id, Genre.all, :id, :genre_name %></td>
				</tr>
				<tr>
					<td>シーン</td>
					<td><%= product.collection_select :scene_id, Scene.all, :id, :scene_name %></td>
				</tr>
				<tr>
					<td>発売日</td>
					<td><%= product.date_field :release_date %></td>
				</tr>
				<tr>
					<td>在庫数</td>
					<td> <%= product.text_field :stock %></td>
				</tr>
			</tbody>
		</table>
		<%= product.submit "更新", class: "btn btn-default btn-sm" %>
		<br>
		<br>
		<%= link_to "戻る", admins_products_path, class: "link" %>
	</div>

	<div class="col-md-6">
		<div id="editproduct_musics_body">
			<%= link_to_add_association '追加', product, :product_musics,
			data: {
				association_insertion_node: '#editproduct_musics_body',
				association_insertion_method: 'append'
			}, class: "btn btn-default btn-sm addbutton" %>
				<%= product.fields_for :product_musics do |music| %>
					<%= render 'editproduct_music_fields', f: music %>
				<% end %>
		</div>
	</div>
	<% end %>
</div>

<style>
h1{
	text-align: center;
}

.addbutton {
	margin-bottom: 10px;
}
.table {
	background-color: #f5f5f5;
	border-radius: 10px;
}
</style>

app/views/products/index.html.erb
<% if flash[:notice] %>
<p class="alert alert-success"><%= flash[:notice] %></p>
<% elsif flash[:warning] %>
<p class="alert alert-warning"><%= flash[:warning] %></p>
<% end %>
<!-- スライドショー -->

<div id="products" class="center">
	<% @slideproducts.each do |product| %>
	<div class="img-width">
		<%= link_to products_show_path(product.id) do %>
		<%= attachment_image_tag product, :music_image, size: "300x300", fallback: "CD_NO_IMAGE.jpg",class: "slideimg" %>
		<% end %>

		<!-- 発売日が１週間以内のものにNEWと表示。登録日に変更も可能 -->
		<% if (Date.today - product.release_date) < 7 %>
		<% end %>
	</div>
	<% end %>
</div>

<!-- 検索メニュー -->
<div class="search col-md-1">

	<%= search_form_for @search do |f| %>
	<h4>検索メニュー</h4>
	<div class="form-group">
		<div class="form-box">
			<label>タイトル</label>
			<%= f.text_field :title_cont,:placeholder => "" ,class: "form"%>
			<br>
			<label>アーティスト</label>
			<%= f.select :artist_id_eq, options_from_collection_for_select(Artist.all.order(:artist_kana), :id, :artist_name), {include_blank: true}, class: "searchable form" %>
			<label>ジャンル</label>
			<%= f.collection_select :genre_id_eq, Genre.all, :id, :genre_name, { include_blank: true, placeholder: "ジャンル"} ,class: "form" %><br>
			<label>プレゼントシーン</label>
			<%= f.collection_select :scene_id_eq, Scene.all, :id, :scene_name, { include_blank: true} ,class: "form" %><br>

			<div class="actions glyphicon glyphicon-zoom-in">
				<%= f.submit "検索",class: "kensaku" %>
			</div>
		</div>
	</div>
	<% end %>
</div>

<div class="container">
	<div class="row">
		<div class="title">
			<h3>商品一覧</h3>
		</div>
		<div class="col-md-9 col-md-offset-1">
			<!-- 並べ替えプルダウン -->
			<table border="2" width="150"  class="sort_box" >
				　<tr>
					　　<th class="sort_link"><%= sort_link(@search, :price, '値段順') %></th>
					　　<th class="sort_link"><%= sort_link(@search, :release_date, '発売日順') %></th>
				　</tr>
			</table>
		</div>

<!-- 商品一覧（ransack） -->
<div id="products">
	<% @result.each do |product| %>

	<div class="product_index">
		<%= link_to products_show_path(product.id) do %>
		<%= attachment_image_tag product, :music_image, class: "", fallback: "CD_NO_IMAGE.jpg", size: "200x200" %>
		<% end %>
		<%= link_to products_show_path(product.id) do %>
		<p class="product_title_color"><%= product.title.truncate(14) %></p>
		<% end %>
		<p><%= product.artist.artist_name %></p>

		<!-- カートアイコンをカート追加のリンクにする -->
		<!-- カートへの追加は非同期処理で行う　-->
		<% if user_signed_in? %>
		<div class="carticon">
			<%= link_to carts_create_path(product_id: product.id), remote: true do %>
			<i class="cart-icon glyphicon glyphicon-shopping-cart" aria-hidden="true" style="color:darkorange"></i>
			<% end %>
		</div>
		<% end %>

		<!-- 発売日が１週間以内のものにNEWと表示。登録日に変更も可能 -->
		<% if (Date.today - product.release_date) < 7 %>
		<span class="new">New</span>
		<% end %>

		<% if product.stock == 0 %>
		<span class="soldout">Soldout</span>
		<% end %>

		<!-- お気に入りの追加・削除をアイコンのクリックで変更できるようにするか検討中 -->
		<% if user_signed_in? %>
			<% if product.favorited_by?(current_user) %>
				<%= link_to favorite_path(product), :method => :delete, remote: true do %>
				<i class="glyphicon glyphicon-heart delete-icon" aria-hidden="true" style="color: red;"></i>
				<% end %>
			<% else %>
				<%= link_to favorites_create_path(product_id: product.id), remote: true do %>
				<i class="glyphicon glyphicon-heart-empty favorite-icon" aria-hidden="true"></i>
				<% end %>
			<% end %>
		<% end %>
	</div>

	<% end %>
</div>
</div>
</div>

<!-- ページャ -->

<div class="col-md-10 col-md-offset-2">
	<%= paginate @result, class: "paginate" %>
</div>

<script>

	$(document).ready(function() {
    	$('.searchable').select2();
	});

</script>

<style>
h4 {
	width: 150px;
}

label{
	margin-top: 10px;
}

.searchable{
	margin-top: 10px;
	/*height: 35px;*/
}
.img-width{
	margin: 11px;
	/*border-style: solid;*/
}

#products {
	margin-left: 30px;
}
.product_title{
	border-bottom: solid 3px;
	background-color: #f2f2f2;
	width: 147px;
}
.sort_box{
	background-color: #f0f8ff;
}
.search{
	margin-top: 10px;
}
.form{
	width: 90%;
	margin-top: 10px;
	margin-bottom: 10px;
}
.kensaku{
	padding:4px;
}
.favorite-icon{
	color: gray;
}
.form-group{
	border-style: 10px;
	border-top: 3px solid #000000;
	width: 200px;
	height: 300px;
	border-style: solid 10px;
}
.form-box{
	text-align: center;
	padding-bottom: 50px;
}
.container {
	width: 1000px;
}
.product_index {
	background-color: #f5f5f5;
	margin: 10px;
	padding: 10px;
	height: 310px;
	width: 220px;
	float: left;
	border-radius: 10px
}

.sort_link {
	color: black
}

.dropdown {
	float: right;
}
.cart-icon{
	height: 30px;
	width: 30px;
	font-size: 24px;
	float: left;
	color: gray;
}
.favorite-icon {
	height: 30px;
	width: 30px;
	font-size: 24px;
	float: left;
}
.delete-icon {
	height: 30px;
	width: 30px;
	font-size: 24px;
	float: left;
}
.new {
	display: inline-block;
	padding: 5px 8px;
	background-color: #ffc0cb;
	border-radius: 3px;
	color: #fff;
	font-size: 14px;
	float: right;
}
.soldout{
	display: inline-block;
	padding: 5px 8px;
	margin-right: 10px;
	background-color: red;
	border-radius: 3px;
	color: #fff;
	font-size: 14px;
	float: right;
}
.slick-list
{
	width: 100%;
}

</style>

app/views/products/new.html.erb
<div class="title">
    <h3>商品登録</h3>
</div>

<% if flash[:notice] %>
<p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>


<% if flash[:warning] %>
<p class="alert alert-success"><%= flash[:warning] %></p>
<% end %>

<br>
<br>
<div class="col-md-offset-2 col-md-10">
<%= form_for(@product) do |product| %>
    <div class="col-md-4">
        <div id="img">
            <label>ジャケット画像</label>
            <%= product.attachment_field :music_image %>
        </div>
        <br>

        <div class="attr">
            <label>タイトル</label>
            <%= product.text_field :title, class: "form" %>
            <br>

            <label>かな</label>
            <%= product.text_field :kana, class: "form" %>
            <br>

            <label>価格</label>
            <%= product.text_field :price, class: "form" %>
            <br>
            <!-- アーティストの入力方法はより良いものに変更予定 -->
            <label>アーティスト</label>
             <%= product.select :artist_id, options_from_collection_for_select(@artists, :id, :artist_name), {include_blank: true}, class: "searchable form" %>
            <br>

            <label>レーベル</label>
            <%= product.collection_select :label_id, Label.all, :id, :label_name, { include_blank: true}, class: "form" %>
            <br>

            <label>ジャンル</label>
            <%= product.collection_select :genre_id, Genre.all, :id, :genre_name, { include_blank: true}, class: "form" %>
            <br>

            <label>シーン</label>
            <%= product.collection_select :scene_id, Scene.all, :id, :scene_name, { include_blank: true}, class: "form" %>
            <br>

            <!-- カレンダーで入力-->
            <label>発売日</label>
            <%= product.date_field :release_date, class: "form" %>
            <br>

            <label>在庫数</label>
            <%= product.text_field :stock, class: "form" %>
            <br>

            <%= product.submit "登録", class: "btn btn-default btn-sm" %>
            <br>
        </div>
        <br>
        <br>
        <%= link_to '戻る', admins_top_path, class: "link" %>
    </div>


    <div class="col-md-6">
        <%= product.fields_for :product_musics do |music| %>
            <%= render 'product_music_fields', f: music %>
            <%= link_to_add_association '追加', product, :product_musics,
            data: {
                association_insertion_node: '#product_musics_body',
                association_insertion_method: 'append'
            }, class: "btn btn-default btn-sm" %>
        <% end %>
    </div>
    <br>
    <br>
<% end %>
</div>

<script>
    $(document).ready(function() {
    $('.searchable').select2();
});

</script>

<style>
#img{
    margin-left: 15px;
}

.attr{
    text-align: right;
    width: 250px;
}

.label{
    display: inline-block;
    width: 100px;
}

.form{

    width: 130px;
}
</style>

app/views/products/show.html.erb
<div class="title">
	<h1>商品詳細</h1>
</div>
<% if flash[:notice] %>
       <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:warning] %>
       <p class="alert alert-danger"><%= flash[:warning] %></p>
<% end %>
<% if flash[:delete] %>
	<p class="alert alert-success"><%= flash[:delete] %></p>
<% end %>

<div class="col-md-2 col-md-offset-3">
	<%= attachment_image_tag @product, :music_image, class: "music_image", fallback: "no_image.jpg", size: "200x200" %>
</div>

<div class="col-md-4">
	<div class="products_show">
		<div class="">商品名：<%= @product.title %></div>
		<div class="">アーティスト：<%= @product.artist.artist_name %></div>
		<div class="">価格：<%= @product.price %>円</div>
		<div class="">レーベル：<%= @product.label.label_name %></div>
		<div class="">ジャンル：<%= @product.genre.genre_name %></div>
		<div class="">総レビュー数：<%= link_to "#product_review" do %>
			<%= @product.reviews.count %><% end %>件</div>
			<% if user_signed_in? %>
				<%= link_to "カートに入れる", carts_create_path(product_id: @product.id), remote: true, class: "btn btn-primary btn-sm cart-icon" %>
			<% end %>

		<br>
		<br>

		<div class="panel panel-default disc_form">
	  		<div class="panel-body">
	  			<% b = @product.product_musics.order(track_num: :asc) %>

	  			<% a = [] %>
	  			<% @product.product_musics.each do |product_music| %>
	  				<% a.push(product_music.disc_num) %>
	  			<% end %>

	  			<% n = a.max %>
	  			<% for i in 1..n do %>
	  				<div>
	  					<p>Disc<%= i %></p>
	  					<% b.each do |product_music| %>
	  						<% if product_music.disc_num == i %>
	  							<p><%= product_music.track_num %> : <%= product_music.music.music_name %></p>
	  						<% end %>
	  					<% end %>
	  				</div>
	  			<% end %>
	  		</div>
		</div>
	</div>
</div>


<% if user_signed_in? %>
<div class="col-md-4 col-md-offset-4">
	<div class="panel panel-default review_form">
		<div class="panel-body">
			<div id="star-rating"></div>
			<%= form_for(@review) do |f| %>
				<label>タイトル</label>
				<%= f.text_field :title %>
				<br><br>
				<label>本　文　</label>
				<%= f.text_area :body %>
				<br><br>
				<%= f.submit "投稿", class: "btn btn-primary btn-sm review-submit" %>
			<% end %>
		</div>
	</div>
</div>
<% end %>


<div class="col-md-4 col-md-offset-4">
	<!-- current_userにレビュー削除機能を追加する -->
	<h3 id="product_review">商品レビュー</h3>
	<% if @product.reviews.length == 0 %>
			<h4 class="space">商品レビューがありません</h4>
	<% end %>

	<% @product.reviews.each do |review| %>
	<div class="panel panel-default review_form">
		<div class="panel-body">
			<div class="review_index">
				<p><%= attachment_image_tag review.user, :profile_image, format: 'jpeg', class: "profile_image", fallback: "no_image.jpg", size: "30x30" %> <%= review.user.user_name %></p>
				<p><strong><%= review.title %></strong><p>
				<p><%= review.body %></p>
			</div>
			<div class="review_created_at">
				<p><%= review.created_at.strftime('%Y年%m月%d日') %></p>
				<br>
				<br>
				<% if review.user == current_user %>
					<%= link_to '削除', review_path(@product), :method => :delete, data: { confirm: '削除しますか？' } , class: "btn btn-danger btn-sm" %>
				<% end %>
			</div>
		</div>
	</div>
	<% end %>
</div>

<style>
	h1{
		text-align: center;
	}
	.products_show {
		background-color: #f5f5f5;
		border-radius: 10px;
		padding: 20px;
		width: 400px;
		margin-top: 20px;
		margin-left: 70px;
	}
	.music_image {
		margin-top: 20px;
		margin-left: 70px;
	}
	.profile_image {
		border-radius: 30px;
	}
	.cart-icon {
		margin-top: 10px;
	}
	.review-submit {
		margin-left: 420px;
	}
	.space {
		margin-bottom: 30px;
	}
	.disc_form {
		width: 250px;
	}
	.review_form {
		width: 500px;
		margin-top: 30px
	}
	.review_index {
		float: left;
		width: 330px;
	}
	.review_created_at {
		float: right;
		text-align: right;
		width: 120px;
	}
</style>